#!/bin/sh

echo "🔍 Vérification du code avec lint-staged..."
npx lint-staged || exit 1

echo "🧪 Vérification composer.json"
composer validate --no-check-publish || exit 1

echo "✅ Tests unitaires rapides"
php bin/phpunit --testsuite=unit || exit 1

echo "✅ Pre-commit checks passed"
